INSERT INTO CURRENCY_EXCHANGE(id, currency_from, currency_to, conversion_multiple, environment)
VALUES(10001,'EUR','BGN',65,'');
INSERT INTO CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(10002,'USD','BGN',85,'');
INSERT INTO CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(10003,'RUB','BGN',100,'');